### ISSUE TITLE
Providing Tribute via homebrew

### ISSUE THREAD

**Issue by kkla320** [nicklockwood/Tribute#6]
Hello,
I really like your package. But I don't understand why I need mint for installation. I would really like to install Tribute via homebrew. Can you provide this installation method?

**Comment by nicklockwood** [comment]
@kkla320 it's just a bit of extra work since I have to manually resubmit a homebrew PR for each update. I guess it's doable though.

**Comment by nicklockwood** [comment]
Well, I tried, but I guess they don't want it.

https://github.com/Homebrew/homebrew-core/pull/102700

**Comment by kkla320** [comment]
Sad to hear :( But thank you very much for the effort :)
